<?php

namespace Proxies\__CG__\Intranet\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Classe extends \Intranet\AdminBundle\Entity\Classe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'id', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'nom', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'description', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'created', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'anneescolaire', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'filiere', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'niveau', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'etudiants', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'plannings');
        }

        return array('__isInitialized__', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'id', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'nom', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'description', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'created', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'anneescolaire', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'filiere', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'niveau', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'etudiants', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Classe' . "\0" . 'plannings');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Classe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function actuelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'actuelle', array());

        return parent::actuelle();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneescolaire(\Intranet\AdminBundle\Entity\Anneescolaire $anneescolaire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneescolaire', array($anneescolaire));

        return parent::setAnneescolaire($anneescolaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneescolaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneescolaire', array());

        return parent::getAnneescolaire();
    }

    /**
     * {@inheritDoc}
     */
    public function addEtudiant(\Intranet\AdminBundle\Entity\Classeetudiant $etudiants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEtudiant', array($etudiants));

        return parent::addEtudiant($etudiants);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEtudiant(\Intranet\AdminBundle\Entity\Classeetudiant $etudiants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEtudiant', array($etudiants));

        return parent::removeEtudiant($etudiants);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudiants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudiants', array());

        return parent::getEtudiants();
    }

    /**
     * {@inheritDoc}
     */
    public function addPlanning(\Intranet\AdminBundle\Entity\Planning $plannings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPlanning', array($plannings));

        return parent::addPlanning($plannings);
    }

    /**
     * {@inheritDoc}
     */
    public function removePlanning(\Intranet\AdminBundle\Entity\Planning $plannings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePlanning', array($plannings));

        return parent::removePlanning($plannings);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlannings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlannings', array());

        return parent::getPlannings();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiliere(\Intranet\AdminBundle\Entity\Filiere $filiere = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiliere', array($filiere));

        return parent::setFiliere($filiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiliere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiliere', array());

        return parent::getFiliere();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(\Intranet\AdminBundle\Entity\Niveauinscription $niveau = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', array($niveau));

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', array());

        return parent::getNiveau();
    }

}
