<?php

namespace Proxies\__CG__\Intranet\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Professeur extends \Intranet\AdminBundle\Entity\Professeur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'id', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'nom', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'prenom', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'datenaissance', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'email', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'matricule', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'telephone', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'genre', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'adresse', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'date', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'compte', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'anneescolaire', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'plannings', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'matieres');
        }

        return array('__isInitialized__', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'id', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'nom', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'prenom', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'datenaissance', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'email', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'matricule', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'telephone', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'genre', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'adresse', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'date', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'compte', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'anneescolaire', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'plannings', '' . "\0" . 'Intranet\\AdminBundle\\Entity\\Professeur' . "\0" . 'matieres');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Professeur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function enseigneMatiere(\Intranet\AdminBundle\Entity\Matiere $mat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'enseigneMatiere', array($mat));

        return parent::enseigneMatiere($mat);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatenaissance($datenaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatenaissance', array($datenaissance));

        return parent::setDatenaissance($datenaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatenaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatenaissance', array());

        return parent::getDatenaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule($matricule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', array($matricule));

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', array());

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompte(\OC\UserBundle\Entity\User $compte = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompte', array($compte));

        return parent::setCompte($compte);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompte', array());

        return parent::getCompte();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneescolaire(\Intranet\AdminBundle\Entity\Anneescolaire $anneescolaire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneescolaire', array($anneescolaire));

        return parent::setAnneescolaire($anneescolaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneescolaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneescolaire', array());

        return parent::getAnneescolaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function addPlanning(\Intranet\AdminBundle\Entity\Seance $plannings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPlanning', array($plannings));

        return parent::addPlanning($plannings);
    }

    /**
     * {@inheritDoc}
     */
    public function removePlanning(\Intranet\AdminBundle\Entity\Seance $plannings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePlanning', array($plannings));

        return parent::removePlanning($plannings);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlannings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlannings', array());

        return parent::getPlannings();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function addMatiere(\Intranet\AdminBundle\Entity\Profmat $matieres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMatiere', array($matieres));

        return parent::addMatiere($matieres);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMatiere(\Intranet\AdminBundle\Entity\Profmat $matieres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMatiere', array($matieres));

        return parent::removeMatiere($matieres);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatieres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatieres', array());

        return parent::getMatieres();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre($genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', array($genre));

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', array());

        return parent::getGenre();
    }

}
