

intranet_professeur:
    resource: "@IntranetProfesseurBundle/Resources/config/routing.yml"
    prefix:   /espace-professeur

intranet_etudiant:
    resource: "@IntranetEtudiantBundle/Resources/config/routing.yml"
    prefix:   /espace-etudiant

internetsite:
    resource: "@InternetsiteBundle/Resources/config/routing.yml"
    prefix:   /

intranet_admin:
    resource: "@IntranetAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

#login:
 #   pattern:   /login
  #  defaults:  { _controller: OCUserBundle:Security:login }

# login_check:
#     pattern:   /login_check

# logout:
#     pattern:   /logout

accueil_intranet:
    pattern:   /intranet
    defaults:  { _controller: OCUserBundle:Info:redirect }


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile