<?php

namespace Internet\siteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PreinscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreinscriptionRepository extends EntityRepository
{
}
