<?php

namespace Intranet\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClasseetudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseetudiantRepository extends EntityRepository
{
}
