<?php

namespace Intranet\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FiliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiliereRepository extends EntityRepository
{
	public function myFindOne($id) {
// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
		->from('IntranetAdminBundle:Matiere', 'a')
		//->where('filieres = :id')
		//->setParameter('id', $id)
		;

		return $qb->getQuery()
		->getResult();
}

}
